name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Install dependencies
        run: |
          sudo apt install -y protobuf-compiler
          go get -u golang.org/x/lint/golint
          go install -v github.com/uudashr/gopkgs/v2/cmd/gopkgs@latest
          go install -v github.com/ramya-rao-a/go-outline@latest
          go install -v github.com/cweill/gotests/gotests@latest
          go install -v github.com/fatih/gomodifytags@latest
          go install -v github.com/josharian/impl@latest
          go install -v github.com/haya14busa/goplay/cmd/goplay@latest
          go install -v google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install -v google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

      - name: Show versions
        run: |
          go version
          protoc --version

      - name: Vet
        run: go vet ./...

      - name: Lint
        run: golint ./...

      - name: Staticcheck
        run: staticcheck ./...

      - name: Test
        run: go test -v ./...

      - name: Build
        run: |
          protoc --proto_path=proto proto/command_service.proto --go_out=proto --go-grpc_out=proto
          go build -v ./...
