name: Go

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        go: [1.19.9, 1.20.4]
    runs-on: ubuntu-latest
    container: golang:${{ matrix.go }}-bullseye

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4

      - name: Show versions
        run: |
          go version

      - name: Vet
        run: |
          go vet ./...

      - name: Test
        run: |
          go test -v ./...

      - name: Build
        run: |
          git config --global --add safe.directory '*'
          go mod vendor
          env GO111MODULE=auto GOFLAGS=-mod=mod go build -v ./...
